package com.tomclaw.openim.main;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 * Solkin Igor Viktorovich, TomClaw Software, 2003-2013
 * http://www.tomclaw.com/
 * @author Solkin
 */
public class AccountsDialog extends javax.swing.JDialog {

  /** Creates new form AccountsDialog */
  public AccountsDialog( java.awt.Frame parent, boolean modal ) {
    super( parent, modal );
    initComponents();
    updateAccounts();
    setLocationRelativeTo( parent );
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Учётные записи");

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/list-add.png"))); // NOI18N
    jButton1.setText("Добавить");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/list-remove.png"))); // NOI18N
    jButton2.setText("Удалить");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/gtk-edit.png"))); // NOI18N
    jButton3.setText("Править");

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Тип", "Логин"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dialog-ok.png"))); // NOI18N
    jButton4.setText("Регистрация");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton2)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton3)
          .addComponent(jButton2)
          .addComponent(jButton4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public final void updateAccounts() {
    DefaultTableModel model = ( DefaultTableModel ) jTable1.getModel();
    int rowCount = model.getRowCount();
    for ( int c = 0; c < rowCount; c++ ) {
      model.removeRow( 0 );
    }
    String[] groups = Storage.accounts.listGroups();
    for ( int c = 0; c < groups.length; c++ ) {
      try {
        String type = Storage.accounts.getValue( groups[c], "type" );
        String login = Storage.accounts.getValue( groups[c], "login" );
        System.out.println( c + ": " + type + " - " + login );
        model.addRow( new String[] { type, login } );
      } catch ( Throwable ex ) {
        System.out.println( ex.getMessage() );
      }
    }
    javax.swing.SwingUtilities.invokeLater( new Runnable() {
      @Override
      public void run() {
        jTable1.updateUI();
      }
    } );
  }

  public final void removeAccount( String type, String login ) {
    String[] groups = Storage.accounts.listGroups();
    for ( int c = 0; c < groups.length; c++ ) {
      try {
        if ( Storage.accounts.getValue( groups[c], "type" ).equals( type )
                && Storage.accounts.getValue( groups[c], "login" ).equals( login ) ) {
          Storage.accounts.removeGroup( groups[c] );
          return;
        }
      } catch ( Throwable ex ) {
        System.out.println( ex.getMessage() );
      }
    }
  }

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  JPopupMenu jPopupMenu = new JPopupMenu();
  String[] plugins;
  try {
    plugins = Storage.settings.listItems( "Plugins" );
    for ( int c = 0; c < plugins.length; c++ ) {
      final String protocol = plugins[c];
      jPopupMenu.add( new JMenuItem( new AbstractAction( protocol ) {
        @Override
        public void actionPerformed( ActionEvent ae ) {
          ( new LoginFrame( OpenIM.mainFrame, protocol, AccountsDialog.this ) ).setVisible( true );
        }
      } ) );
    }
  } catch ( Throwable ex ) {
  }
  jPopupMenu.show( jButton1, 0, jButton1.getHeight() );
}//GEN-LAST:event_jButton1ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    ( new RegisterFrame( OpenIM.mainFrame, true, this ) ).setVisible( true );
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int selectedIndex = jTable1.getSelectedRow();
    if ( selectedIndex != -1 ) {
      DefaultTableModel model = ( DefaultTableModel ) jTable1.getModel();
      String type = ( String ) model.getValueAt( selectedIndex, 0 );
      String login = ( String ) model.getValueAt( selectedIndex, 1 );
      removeAccount( type, login );
      updateAccounts();
      Storage.saveAccounts();
      OpenIM.mainFrame.removeAccountRoot( OpenIM.mainFrame.getAccountRoot( type, login ) );
    }
  }//GEN-LAST:event_jButton2ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
